name: Update task for push action

on:
  push:
    branches-ignore:
      - master

jobs:
  kanboard:
    uses: moogur/all-workflows/.github/workflows/kanboard.yml@master
    secrets: inherit
    with:
      kanboard_columns: '81,82,83,84,85,86,-'
      project_type: 'multi_branch'
      event_type: 'push'
